version: "3.3"

services:
  pollar-database:
    image: mariadb
    container_name: pollar-database
    restart: always
    env_file:
      - ./.env
    ports:
      - "3306:3306"
    volumes:
      - ./src/db/pollar.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend
  pollar-api:
    container_name: pollar-api
    depends_on:
      - pollar-database
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
    networks:
      - backend
    environment:
      - PORT=3000
    ports:
      - "3000:3000"
networks:
  backend:
