version: "3.3"

services:
  db:
    build: ./db/
    restart: always
    env_file:
      - ./config/db.env
    ports:
      - "3306:3306"
    networks:
      - backend
    volumes:
      - ./db/pollar.sql:/docker-entrypoint-initdb.d/init.sql
  app:
    container_name: pollar-api
    depends_on:
      db:
        condition: service_started
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
    restart: always
    networks:
      - backend
    environment:
      - PORT=3000
    ports:
      - 3000:3000
networks:
  backend:
