version: "3.3"

services:
  app:
    container_name: vote-api
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
    restart: always
    environment:
      - PORT=3000
    ports:
      - 3000:3000
